# Name of your application. Used to uniquely configuring Traefik and app containers.
# Your Dockerfile should set LABEL service=the-same-value to ensure image pruning works.
service: hello-symfo

# Name of the container image.
image: pauulog/hello-symfo

registry:
  server: docker.io
  username: pauulog
  password: <%= ENV.fetch("MRSK_REGISTRY_PASSWORD") %>

# Deploy to these servers.
servers:
  web:
    hosts:
      - <%= ENV.fetch("WEB_HOST_1") %>

env:
  secret:
    - DATABASE_URL
    - APP_ENV
    - APP_SECRET

traefik:
  args:
    accesslog: true
    accesslog.format: json

healthcheck:
  path: /up
  port: 80

accessories:
  postgresql:
    image: postgres:15-alpine
    host: <%= ENV.fetch("WEB_HOST_1") %>
    port: 5432
    private: true
    env:
      clear:
        POSTGRES_USER: hello
        POSTGRES_DB: hello
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/lib/postgresql/data/:/var/lib/postgresql/data/
